### ISSUE TITLE
make wiki page

### ISSUE THREAD

**Issue by mildshower** [step-batch-7/runtimeTerror-risk#1]
making wiki pages

acceptance criteria:

- [x]  having a mockup page and mockup scan copies should be uploaded there

- [x] Having a user flow page and user flows should be uploaded there

- [x] A how to play page
- [x] Dev-setup page and there should be setting up commands, plugins to be installed, node version, vs-code version

**Comment by bsanthoshkumar** [comment]
spelling mistake in repository name.
--git clone https://github.com/step-batch-7/runtimeTerro-risk.git

**Comment by bsanthoshkumar** [comment]
Draw the mochups thicker in mochups.(it is not visible)

**Comment by mildshower** [comment]
dev page:
  instead of 'text editor', use 'code editor'
  tell about eslint and it's version and also mention that linter rules are already available inside the repo
  tell about the project skeleton(directory structure) and which directory is dedicated for which work
mockups page: 
  looks good now 😊
