### ISSUE TITLE
View the current game stage(claim(1st)/reinforcement(2nd)/final(3rd))

### ISSUE THREAD

**Issue by bsanthoshkumar** [step-batch-7/runtimeTerror-risk#11]
As a player
    I want to know the current stage of the game
    So that I can keep track of game progress

### Assumption
- a game page is already made

### In Scope
- Stage Name (claim or reinforcement or final) with number

### Acceptance Criteria

- [x] Criteria 1

- Given I want to check the current stage
- When I am in the game page
- Then I should see the current game stage at top-center of the game page

**Comment by photongupta** [comment]
There should be some space between the text and the border in order to read properly.
The format of viewing the text(stage) should be according to the following example-
Claim (1st stage)
fix it up.
