### ISSUE TITLE
spike on moment js

### ISSUE THREAD

**Issue by satheesh-chandran** [step-batch-7/runtimeTerror-risk#7]
spike on moment js that helps formatting date and time
 - [x] Advantages
- [x]  Disadvantages
- [x]  How it is helpful in our project

**Comment by bsanthoshkumar** [comment]
[Moment spike documentation](https://docs.google.com/document/d/1Wc73-MfEYdeiUzQ46ALocq8TBObdoEURXLPa17nDcqE/edit?usp=sharing)
-by Santhosh
